### ISSUE TITLE
Unable to get it working on Ubuntu 14.04

### ISSUE THREAD

**Issue by computermaster0101** [raelgc/es-logo#1]
Hello,

I followed the instructions in the readme but cannot get the theme to update. I have verified using other themes are working by switching to the spinfinity logo splash screen. Please contact me at your convenience, I'd be happy to work together to resolve the issue. Thank you in advance!

**Comment by raelgc** [comment]
Hi @computermaster0101 and thanks for reporting this!

Just to double check: after select `es-logo` for default theme, will `sudo upate-initramfs -u` make any difference?

In fact, I tested this theme on 16.04 and 18.04, but it should work without issues on 14.04. 

Anyway, I'll download a 14.04 iso and install in a VM to test.

**Comment by computermaster0101** [comment]
I've installed ubuntu-logo-scale-2. After some review i've found that when i set ubuntu-logo-scale-2 there is an /etc/alternatives/default.plymouth.grub in addition to /etc/alternatives/default.plymouth but when i set es-logo. I've attempted to add the link myself for /usr/share/plymouth/themes/es-logo/es-logo.grub and /etc/alternatives/default.plymouth.grub. Doing ln -s breaks the link group. Doing update-alternatives --install for default.plymouth.grub fails because default.plymouth.grub cant be master, its a slave of default.plymouth. currently im looking to the link group. Im new to Plymouth though.

**Comment by raelgc** [comment]
@computermaster0101 Is `14.04` still using `/lib/plymouth/themes` for themes instead of `/usr/share/plymouth/themes`? If yes, just follow the instructions again replacing the folder path.

**Comment by computermaster0101** [comment]
performed the remove, moved /usr/share/plymouth/themes/es-logo to /lib/plymouth/themes/, updated es-logo.plymouth with substituted paths, then performed install with substituted paths. When i switch to es-logo, the default.plymouth.grub is still not linked. I double checked the permissions of both es-logo and  ubuntu-logo-scale-2 (just in case) and they matched. 

Command used to install:
sudo update-alternatives --install /lib/plymouth/themes/default.plymouth default.plymouth /lib/plymouth/themes/es-logo/es-logo.plymouth 100

##UPDATE##
Performing the above steps and following up with update-initramfs -u worked.

Thank you for the fast resolution!

**Comment by raelgc** [comment]
I'm glad it worked!

I'll update the `README` with instructions to 14.04 and the missing `update-initframfs -u` command.
