### ISSUE TITLE
Ubuntu Server 16.04 steps lead to black screen

### ISSUE THREAD

**Issue by computermaster0101** [raelgc/es-logo#2]
on new Ubuntu Server 16.04 with no packages selected during install and no swapfile I ran 

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install plymouth-themes plymouth-label
sudo git -C /usr/share/plymouth/themes clone https://github.com/raelgc/es-logo.git
sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/es-logo/es-logo.plymouth 100
sudo update-initramfs -u

to install the splash screen and then 

sudo sed -i.orig 's/LINUX_DEFAULT=""/LINUX_DEFAULT="quiet splash"/' /etc/default/grub
sudo update-grub

to enable the graphical splashscreen at boot. The splashscreen displays however when it clears I only have a black screen. Any thoughts?

**Comment by raelgc** [comment]
Hi @computermaster0101. This repository is just a theme for plymouth. If you can see the graphical splashscreen, so it works. After it, it's no more related to plymouth.

Do you have installed Xorg, a login manager and a desktop environment?
